services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: gestao_estabelecimento
    ports:
      - "3307:3306"
    volumes:
    - mysql_data:/var/lib/mysql

  gestao_app:
    build: .
    ports:
      - "8082:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gestao_estabelecimento?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: senha123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SERVER_PORT: 8081
    depends_on:
      - mysql

volumes:
  mysql_data: