
spring.datasource.url=jdbc:mysql://localhost:3307/gestao_estabelecimento?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=senha123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8081

# Logs SQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


#spring.datasource.url=jdbc:h2:mem:gestaoestabelecimento
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=gestao
#spring.datasource.password=password

#Acesso H2
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:init.sql
